"""initial schema

Revision ID: 52b3c231f0e0
Revises: 
Create Date: 2026-07-24 23:58:27.166574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b3c231f0e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('SCRAPE', 'CSV_IMPORT', name='analysissource'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('stage', sa.Enum('INGEST', 'ENRICH', 'ANALYZE', name='analysisstage'), nullable=True),
    sa.Column('error_code', sa.Enum('PROFILE_PRIVATE', 'PROFILE_NOT_FOUND', 'EMPTY_HISTORY', 'INVALID_EXPORT', 'INTERNAL_ERROR', name='errorcode'), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_index(op.f('ix_analyses_username'), 'analyses', ['username'], unique=False)
    op.create_table('films',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('letterboxd_slug', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('directors', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('production_countries', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_letterboxd_slug'), 'films', ['letterboxd_slug'], unique=True)
    op.create_index(op.f('ix_films_tmdb_id'), 'films', ['tmdb_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_analysis_id'), 'profiles', ['analysis_id'], unique=True)
    op.create_table('watched_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('letterboxd_slug', sa.String(length=300), nullable=True),
    sa.Column('watched_on', sa.Date(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_rewatch', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_entries_analysis_id'), 'watched_entries', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_watched_entries_film_id'), 'watched_entries', ['film_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_entries_film_id'), table_name='watched_entries')
    op.drop_index(op.f('ix_watched_entries_analysis_id'), table_name='watched_entries')
    op.drop_table('watched_entries')
    op.drop_index(op.f('ix_profiles_analysis_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_films_tmdb_id'), table_name='films')
    op.drop_index(op.f('ix_films_letterboxd_slug'), table_name='films')
    op.drop_table('films')
    op.drop_index(op.f('ix_analyses_username'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
